initialized the website with rails and mongoDB
yeonchae62/LIVE pull request #2
Opened 2024-02-05 04:28 UTC by xiuyu-lana

2024-02-05 16:16 UTC, nilo-tamu commented on config/initializers/content_security_policy.rb
What is the purpose of this file?

2024-02-05 16:40 UTC, nilo-tamu requested changes
As per team conversation, holding off on PR approval until unit tests are passing (please attach test evidence in PR body).

2024-02-05 16:41 UTC, nilo-tamu commented
In the future we can also revise the necessity of some of these files in the code base so that it becomes cleaner.

2024-02-12 02:03 UTC, xiuyu-lana commented
Two modifications: 1. add validations for the game title and URL; 2. add tests for models, controllers, views, and requests (under LIVE/spec folder). To run all tests, run `rspec` under LIVE folder. As shown in the image below, all tests passed. Please review@nilo-tamu 
<img width="513" alt="IMG_6507" src="https://github.com/yeonchae62/LIVE/assets/98288844/6073b0b0-3971-490e-a11f-e4d55df9c799">

2024-02-15 04:04 UTC, nilo-tamu commented
Also are there Cucumber tests in here? Trying to observe if that is something that could be inserted at this point or if it should come ion later

2024-02-15 04:11 UTC, nilo-tamu approved these changes

2024-02-15 04:15 UTC, merged